export const STRINGS = {
  common: {
    loading: "Loading...",
    edit: "Edit",
    continue: "Continue",
    skipForNow: "Skip for now",
    viewAll: "View all",
  },
  tabs: {
    home: "Home",
    progress: "Progress",
    learn: "Learn",
    journal: "Journal",
    profile: "Profile",
    posts: "Posts",
  },
  progress: {
    headerTitle: "Progress",
    weightCard: {
      label: "Current weight",
      defaultWeight: "82.4",
      defaultUnit: "Kg",
      defaultChange: "+0.2 kg",
      defaultLastLogged: "Last logged 11 Sep 2026",
    },
    goal: {
      title: "Your Goal",
      subtitle: "Tracking your progress toward target.",
      targetLabel: "Target",
      byLabel: "By",
      paceLabel: "Pace",
      defaultTarget: "55",
      defaultTargetUnit: "Kg",
      defaultByDate: "7 May",
      defaultByYear: "2026",
      defaultPace: "moderate",
      defaultPaceUnit: "0.5 kg/wk",
    },
    weightChart: {
      timeframes: ["W", "M", "6M", "Y"] as const,
      yTicks: ["90", "85", "80", "75", "70"] as const,
      months: ["Apr", "May", "Jun", "Jul", "Aug", "Sep"] as const,
      average: "Average",
      defaultTooltipValue: "82",
      defaultTooltipUnit: " kg",
      defaultTooltipDate: "1-7 May 2016",
    },
    bmi: {
      title: "BMI",
      defaultCategory: "Normal",
      defaultBmiValue: "20.6",
      defaultHeight: "137cm",
      healthyDescription: "Your BMI is within the healthy range.",
      heightPrefix: "Height: ",
      footerCaption: "Your BMI is calculated based on this height.",
    },
    recentLogs: {
      title: "Recent logs",
      defaultLogs: [
        {
          id: "1",
          weight: "82.4",
          unit: "Kg",
          waist: "waist 91.2 cm",
          date: "Thursday 11 Sep 2026",
          change: "0.4 kg",
          changeType: "decrease" as const,
        },
        {
          id: "2",
          weight: "82.4",
          unit: "Kg",
          date: "Thursday 11 Sep 2026",
          change: "+0.2 kg",
          changeType: "increase" as const,
        },
        {
          id: "3",
          weight: "82.4",
          unit: "Kg",
          date: "Thursday 11 Sep 2026",
          change: "0.4 kg",
          changeType: "decrease" as const,
        },
      ],
    },
    walkthrough: {
      title: "Walkthrough",
      items: [
        {
          id: "1",
          tag: "Pen",
          title: "How to dispose of the pen or needle safely?",
        },
        {
          id: "2",
          tag: "Guide",
          title: "Understanding your daily weight fluctuations",
        },
        {
          id: "3",
          tag: "Tips",
          title: "Best practices for consistent body measurements",
        },
      ],
    },
    measurement: {
      title: "What is your current\nweight?",
      subtitle:
        "We’ll use this to set up your Progress tab and track your starting point.",
      unitKg: "kg",
      unitLb: "lb",
      pillKg: "Kg",
      pillLb: "St, lb",
    },
  },
} as const;
